add_test( [==[stem strips directory and all extensions]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[stem strips directory and all extensions]==]  )
set_tests_properties( [==[stem strips directory and all extensions]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[cigar_op and cigar_len decode raw BAM uint32_t]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[cigar_op and cigar_len decode raw BAM uint32_t]==]  )
set_tests_properties( [==[cigar_op and cigar_len decode raw BAM uint32_t]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[cigar_encode round-trips correctly]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[cigar_encode round-trips correctly]==]  )
set_tests_properties( [==[cigar_encode round-trips correctly]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[count_gaps empty cigar returns 0]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[count_gaps empty cigar returns 0]==]  )
set_tests_properties( [==[count_gaps empty cigar returns 0]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[count_gaps counts only INS/DEL ops >= threshold]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[count_gaps counts only INS/DEL ops >= threshold]==]  )
set_tests_properties( [==[count_gaps counts only INS/DEL ops >= threshold]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[count_gaps ignores non-gap ops (M, S, H, N, =, X)]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[count_gaps ignores non-gap ops (M\, S\, H\, N\, =\, X)]==]  )
set_tests_properties( [==[count_gaps ignores non-gap ops (M, S, H, N, =, X)]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[count_gaps threshold=1 counts all INS and DEL]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[count_gaps threshold=1 counts all INS and DEL]==]  )
set_tests_properties( [==[count_gaps threshold=1 counts all INS and DEL]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[decantiles on empty vector returns all zeros]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[decantiles on empty vector returns all zeros]==]  )
set_tests_properties( [==[decantiles on empty vector returns all zeros]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[decantiles on single element returns that value for all]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[decantiles on single element returns that value for all]==]  )
set_tests_properties( [==[decantiles on single element returns that value for all]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[decantiles on 10 sorted values [1..10]]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[decantiles on 10 sorted values \[1..10\]]==]  )
set_tests_properties( [==[decantiles on 10 sorted values [1..10]]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[decantiles values are monotonically non-decreasing]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[decantiles values are monotonically non-decreasing]==]  )
set_tests_properties( [==[decantiles values are monotonically non-decreasing]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
add_test( [==[decantiles on uniform distribution P50 equals median]==] /home/vinzenz/dev/aln_qc/build-pixi/tests/test_gapstats [==[decantiles on uniform distribution P50 equals median]==]  )
set_tests_properties( [==[decantiles on uniform distribution P50 equals median]==] PROPERTIES WORKING_DIRECTORY /home/vinzenz/dev/aln_qc/build-pixi/tests)
set( test_gapstats_TESTS [==[stem strips directory and all extensions]==] [==[cigar_op and cigar_len decode raw BAM uint32_t]==] [==[cigar_encode round-trips correctly]==] [==[count_gaps empty cigar returns 0]==] [==[count_gaps counts only INS/DEL ops >= threshold]==] [==[count_gaps ignores non-gap ops (M, S, H, N, =, X)]==] [==[count_gaps threshold=1 counts all INS and DEL]==] [==[decantiles on empty vector returns all zeros]==] [==[decantiles on single element returns that value for all]==] [==[decantiles on 10 sorted values [1..10]]==] [==[decantiles values are monotonically non-decreasing]==] [==[decantiles on uniform distribution P50 equals median]==])
